
/* global CKEDITOR, TurndownService */
var turndownService = new TurndownService({
  bulletListMarker: "-",
  headingStyle: "atx",
});
// Configure CKEditor window
CKEDITOR.replace("wordup", {
  dataIndentationChars: "  ",
  format_tags: "p;h1;h2;h3;h4;h5",
  height: 325,
  removeButtons:
    "Underline,Strike,Subscript,Superscript,Anchor,Styles,Specialchar",
  toolbarGroups: [
    { groups: ["basicstyles"], name: "basicstyles" },
    { groups: ["links"], name: "links" },
    { groups: ["list"], name: "paragraph" },
    { groups: ["list"], name: "insert" },
    { groups: ["mode"], name: "document" },
    { groups: ["styles"], name: "styles" },
  ],
});

function scrubber(string) {
  brandsArray = ["ACCUPURE","ADOPTAPET.COM","ALIMENTARIUM","ALL4YOUTH","ALY","AOV","ARTESANO","ASSOCIATION SPORTS ET LOISIRS NESTLE (ASLN)","ATRIUM INNOVATIONS","AVANTE","AVEIAS ORGANICAS","BANANITA DOLCA","BANCO SABADELL","BARKAT","BASIX","BIBITE","BIGGIE","BIO THERAPEUTIC DRAINAGE","BIOINMUNIS","BIOVIDA","BISHULIM","BISTRENOK","BLACK ROAST","BLAZHENSTVO","BLUE CROSS","BONUS","BREEDER","BUBCHEN","BUONA-LA-VITA","BUSY BONES","CADIPRO","CAFE DE OLLA","CARAMELLE","CEREAVENA","CHIPSI","CHOCOMIEL","COGNITA GOLD","COLD BREW","COLLECTSYA","COMECAR SAUDAVEL","COMPENSA","CONFITERIA","CREMOSITAS","DAR NATURY","DAYEM","DONA JUANITA","DOUGLAS LABS","DPA","DULCE RECETA","DULCI CREMA","ECUATEUR","EL CASTELL","ELEGIS GLACIAR","ERLENBACHER","ESENCIAL","EVENTS","EVERROOT","FDGARD","FIBER CHOICE","FINE DINING LOVERS","FLACHKRAKER","FOLLOW UP","FORMULA 4 SUCCESS","FRESH & FRUITY","FREUNDSCHAFTS-WOCHEN","FRUCHTMINIS","FRUTESS","FRUTTI","GAUCHITAS","GLUTEN FREE","GOLD CRISP","GOODNES","GROWING UP","HEALTHY KIDS","HEARTLAND","HEAVENLY CREAMER","HENRI","HRYLIAZH SHOKOLADNYI","IBGARD","INSTA CREM","IRON PLUS","ITINERARIES OF TASTE","JACKY","JANNYS","JEDE","KHRUM","KLEAN","KOFE S MOLOKOM","KREEM MEE","KRUKTA","LA CHOZA","LA PRADERA","LACTALIS","LINHA ZERO","LITTLE BREAKS","MAI CUI PIAN","MANY","MEDIA CREMA","METROGELIS","METVIX","MEZEAST","MIETTE","MIXES","MODULIFE","MOMMALOVE","MORADITAS","MUSEO","NAV","NCARE","NESTLE NUTRITION INSTITUTE (NNI)","NESTLE RECIPES","NESTROVIT","NEUTRALITY","NQAC D","NUTRI PRO","NUTRIPAK","NUTRITIONAL ACADEMY","ONCO","OPTILAC","ORIGENS","ORTHICA","OUTSIDERS","PANETTONES","PENSION FUND","PHLOGENZYM","PLIAGLIS","PROLINE","PROOF","PURA FRUTA","PUTESHESTVYE","QUENCH","QUOTIDIA","READYREFRESH","RECCHITELLE","RECETAS NESTLE","RECETTE OUBLIEE","RED JAK","RED LINE","REGIONAL SPRING WATER","REMFRESH","RESERVA MEXICANA","REVENA","ROKOKO","ROSEMARY","RSW","RUFFS","RUMBO SEGURO","SALINIS","SAXON","SCHAR","SEATTLE'S BEST","SENSATSII","SHSH","SILKIS","SNACKMIX","START HEALTHY STAY HEALTHY","SWEET HABIT","TEA-MATE","TEA-TIME","TOP","TORONTO","TROPHIC","TUC","U4HK","VACANTAZAS","VEM DE BOLO","VISITA MEDICA","VIT","VITA","VITAL PROTEINS","VITALAC","VIVÉE","VOSTORG","WELL ASSIST","WELLNESS","WILD ROSE","WILDSCAPE","YOU'LL LOVE COLES","YOUTH INITIATIVE","ZOORPRESA","GLUTINO","C","CRICRI","DANKY","DREUMESMELK","ESKIMO","NESSUCAR","XXX","NERO","ROSSANA","MONOPRIX","AFFINIBASE","BLUE BOTTLE","CHAMELEON","FRUTY FRESCO","TOKI","YUS","BRASILIA","CAILLER","CHRISTINA","DALLMAYR","MUSUN","NESCAFE","SUNRISE","NESPRESSO","NESTEA","BOLERO","BONKA","BRASA","BRITE","CAP JUNJUNG","CARNATION","CARO","COFFEE-MATE","CREMORA","ECCO","EKO","EL CHANA","EVERYDAY","Fruita Vitals","GOD MORGON","HUESITOS","KREMATOP","MILO","MOKAMBO","NATURA","Natural Bliss","NESFRUTA","NESTLÉ","ORCHARD","ORZORO","PENSAL","RICORE","STARBUCKS MEDIUM","TOFINA","ASSIS","VITAMINCHIK","BONJORNO","BUONDI","CAFEDOR","CAFELIA","CORE","GOODHOST","INCAROM","LA ESTRELLA","LIBBY'S","LINDE'S","LOUMIDIS","MONOPOIKILIAKOS","PAPAGALOS","PERO","RICORY","SANTA CRISTINA","SICAL","WHIP MATE","ZOEGAS","PRESTO","SWEET LEAF","TOFA","TRADEWINDS","VEEKREME","YUKERY","INTERNATIONAL ROAST","VITALITY","ILLY","LANDWER","BEIT HASHITA","STARBUCKS","Cinnamon Toast Crunch","Force","Harvest Home","Rice Pops","CARLOS V","LIFITA","AVENA Y MÁS","BAR ONE","BOX BOWLS","BRAN FLAKES","CEREAL GOLD","CHEERIOS","CHOCAPIC","CHOKELLA","CINI-MINIS","CLUSTERS","COCOA PUFFS","COOKIE CRISP","CORN FLAKES","COUNTRY CORN FLAKES","CRISP RICE","CRUNCH","CURIOUSLY CINNAMON","DUO","ERDBEER MINIS","ESTRELITAS","FIBRE 1","FITNESS","FITNESSE","FRUTINA","GO FREE","GOLD","GOLD FLAKES","GOLDEN GRAHAMS","GOLDEN MINIS","GOLDEN NUGGETS","HONEY GOLD","HONEY STARS","KANGUS","KHRUTKA","KOKO KRUNCH","KOSMOSTARS","LA LECHERA","LION","LUCKY CHARMS","MIX","MOCA","MUSLI","NESCAU","NESFIT","NESPLUS","NESQUIK","OATS & MORE","SHREDDED WHEAT","SHREDDIES","SNOW FLAKES","STRAWBERRY MINIS","TOFFEE CRISP","TRIO","TRIX","TROPIKAL MEYVELI MUSLI","ZUCOSOS","BRAN PLUS","FLEMINGS","FRUITY BITES","LE SNAK","MUESLI","O&G","OAT CRISP","OAT FLAKES","OATBRITS","OATS","PLUS","UNCLE TOBYS","VITA BRITS","MALT O MEAL","ALDI","ASDA","BRAKES","CENTRA","CO-OP","CROWNFIELD","DUNNES","JACK'S","MORRISONS","SAINSBURYS","SUPERVALU","TESCO","WAITROSE","WOOLWORTHS","BLACK KNIGHT","HSU FU CHI","HSU FU CHI SASHIMA","CRIOLLITA","3 PAULY","ALLEN’S","CHEWMIX","BALATON","AERO","BOCI","MELBA","PARIZSI","BOLIBOMBA","PUMPEDLI","AMBASSADOR","CUISINE","FEMINA","FRIGOR","LES RECETTES DE L'ATELIER","SUBLIM","EL CASTILLO","CHOCOTON","D'ONOFRIO","LENTEJAS","MOROCHAS","MOTTA","SUBLIME","BATON","CARIBE","GAROTO","IT COCO","OPERETA","SERENATA DE AMOR","SURREAL","TALENTO","HEARDS","CHENG WEI KONG JIAN","DODO","DR. BEAR","GOODNESS OF NATURE","HOUQIE","NONG99","QIANCENGSU","LANVIN","MABEL","ALTEZA","GRILL","KUKY","MC KAY","MOROCHA","TRITON","100 GRAND","ABUELITA","AFTER EIGHT","ALL STARS","ALMONRIS","ALPINO","AMOR","ANIMAL BAR","ANTICOL","BABY RUTH","BESO DE AMOR","BIG TURK","BLACK MAGIC","BLOND","BLUE RIBAND","BONO","BREAKAWAY","BROS","BUTTER MENTHOL","BUTTERFINGER","CAJA ROJA","CAJETOSO","CALIPSO","CAN CAN","CAPRI","CARAMAC","CHAOBII","CHARGE","CHOCLAIT CHIPS","CHOCO CROSSIES","CHOCOLATE LOG","CHOCOPOSTRE","CHOKITO","CHUNKY","CIOCOBLOCCO","CIPIRIPI","CLASSIC","CLUB","COCO","COCOA PLAN","COCOSETTE","COFFEE CRISP","CRISP","CUICUISHA","DAIRY BOX","DAISY","DAMAK","DEDITOS","DESSERT","DIPLOMATA","DOLCA","DORE","DRIFTER","EXTRAFINO","FAVOURITES","FRESKAS","FRISCO","FRUTIPS","GALAK","GOLDEN ROUGH","GOOBERS","GOODMIX","GRAND CHOCOLAT","HIT","IDEAL","IMPERIAL","JITEN DAR","JOE","KIT KAT","KOHLER","LARIN","LOLLO","LZ","MACARENA","MACKINTOSH'S","MANICERO","MARIA","MAXIBON","MENIER","MILKYBAR","MINI","MINT PATTIE","MIRAGE","MIX-UPS","MORENITAS","MUECAS","MUNCH","MUNCHIES","MURA","NEGRESCO","NEGRITA","NESTLÉ 1927","NIPS","NUTS","OH HENRY","PARTY","PASSATEMPO","PASSIONS","PIXIE CARAMEL","PLATILLOS","POLLY","POLO","POP","POSTRES","PRALINATO","PRESTIGIO","PRINCESA","PRINCESSA","QUALITY STREET","QUECHAOKAFEILE","RAISINETS","REAL","RICAS","ROLO","SAHNE NUSS","SALTINAS","SAVOY","SAVOY BOLERO","SAVOY CRICRI","SAVOY GALAK","SAVOY PING PONG","SAVOY SAMBA","SAVOY TORONTO","SENSACAO","SHARK","SMARTIES","SMASH","SNOCAPS","SOOTHERS","STARZ","SUFLAIR","SUNDY","SUPER 8","SUPER FIGHTERS","SUPER FLYERS","SUPER REDS","SURPRESA","SUSY","SWISS","TABLETAS CHOCOLATERIA","TANGO","TEX","THROATIES","TIN LARIN","TOFFO","TOLA","TOLL HOUSE","TOSTINES","TRENCITO","TRIANGULO","TURTLES","VAFERITO","VIOLET CRUMBLE","WALNUT WHIP","YES!","YORKIE","ZOOLOGIA","BANANY","DELI","DELISSA","KASTANY","KOCICI JAZYCKY","KOFILA","KOKO","LENTILKY","MARASKA","MARGOT","MILANSKA SMES","MILENA","MODRE Z NEBE","NUGAT","NUGETA","ORIENT DEZERT","ORION","PRALINKY","STUDENTSKA","STUDENTSKA PECET","APROPO","ARGALIOT","BAMBA","BISSLI","CRISPY","DUBONIM","HABAYIT","LACHMIT","OSEM","PETIT BEURRE","SUNNY WHEAT CRACKERS","BON PARI","DOLCECA","FOX'S","FRUIT JOY","HASLERKY","JOJO","KOALA","KOMILFO","LIFESAVERS","LIPO","PLAISTOWE","QUICK-EZE","SZERECSEN","ZORA","BACETTI","BACI","FONDENTE LUISA","FONDENTI","GRIFO","ORE LIETE","PERUGINA","TABLO","TRASIMENO","POWERBAR","RODNYE PROSTORY","RGS","ROSSIYA","SUDARUSHKA","ZOLOTAYA MARKA","RANDOMS","ROWNTREES","SAMBA","PING PONG","SFINX","SPARTA","ARTEK","PALITRA","ROMASHKA","STOZHARY","SVITOCH","ZORIANE SIAIVO","ROLL-UPS","BOTTLE CAPS","GOBSTOPPER","LAFFY TAFFY","LIK-M-AID FUN DIP","NERDS","PIXY STIX","RUNTS","SHOCKERS","SPREE","SWEETARTS","WONKA","DOCELLO","POPCO","CHERVONYI MAK","Crema de leche","FUSSELL'S","Ovaltine","OTHERS","BUITONI","KREMLY","OHYO","MARONSUI'S","MAGGI","MORELIA","CERGAS","NESQINO","A+","ACTICOL","ACTICOR","ACTIPLUS","ACTI-TRANSIT","ACTI-V","AISIPEI","AMANECER","BEAR BRAND","BETTY","BIOVITA","BISTROFF","BLISS","BUNYAD","BUTTERFLY","CALCIUM PLUS","CAMPESINA","CANPROLAC","CERELAC","CEREVITA","CHAMBINHO","CHAMBOURCY","CHAMYTO","CHANDELLE","CHIQUITIN","CHUCKIE","CREAM","CREATIONS","CREME DE LEITE","DAIRY FARM","DALKY","DANCOW","EAGLE","EL RODEO","ESSENTIA","FARINHA LACTEA","FIORELO","FLAIR","FLANBY","FOLIE DE FRUITS","FOOD LION","FRESH","FRUTTOLO","GASTRO PROTECT","GLORIA","GOLD CROSS","GOLDEN MORN","GREEN BUTTERFLY","GREGO","GRIEGO","HIGHLANDER","HIRZ","IL LATTE CONDENSATO","JUST MILK","KLIM","LA LAITIÈRE","LA VAQUITA","LC1","LE VIENNOIS","LE YAOURT A LA GRECQE","LECHE CONDENSADO","LECHE IDEAL","LECHE SUR","LECHERO","LEITE MOCA","LONGA VIDA","MILCHMÄDCHEN","MILKMAID","MILKPAK","MOCINHA","MOLICO","MUNCH BUNCH","NEIGE DE LAIT","NESCAO","NESPRAY","NESTOMALT","NESTON","NESTUM","NESVITA","NIDO","NINHO","NONA","NUBE","NUTRI","NUTRI RINDES","NUTRI-RINDE","NUVEM DE LEITE","OMEGA PLUS","RICA CHICHA","RICACAO","RINDE","SCHOOL","SHIMMY","SKI","SOLEIL","SPROUTS FARMERS MARKET","STALDEN","SUNSHINE","SUPLIGEN","SVELTESSE","SVELTY","TIP TOP","TONIMALT","TOTAL DIGEST","TREAT","TWIN","VASCOLET","VELOURS DE CREME","VIENNOIS","VIKING MELK","WELLNESS CLUB","WHITE LILY","YAOS","YIYANG","YIYUE","YIYUN","YOCO","YOGGI","YOGU YOGU","NESMALT","GRANKO","ANCHOR","HANNAFORD","MADAME GOUGOUSSE","PAK FOOK","WINIARY","ALIPENDE","AUCHAN","EROSKI","HOME BRAND","KROGER","MARKET PANTRY","MILBONA","PRICE RITE","PUBLIX","SAFEWAY","SHOP RITE","VELVET","WAL MART","CAMPESTRE","DONA MARI","DONGUSTO","MALHER","DELISSIO","PIZZA FIESTA","SOSKO","ZACIN C","HÄLSANS KÖK","LIFE CUISINE","FABADA LITORAL","MOUSLINE","MIVINA","BOFROST","CALIFORNIA PIZZA KITCHEN","CONSOMATE","FINDUS","HOT POCKETS","LEAN POCKETS","TORCHYN","WAGNER","DOROT","HALSANSKOK","HEAT & SERVE","ISRAELI ","MANA CHAMA","MEALS-ON-THE GO","PERFECTO","APETITO","BARACKE","BELL","BONJOUR","CASA GIULIANA","CROSSE & BLACKWELL","DIGIORNO","GARDEN GOURMET","HARVEST GOURMET","HERTA","HIESTAND","LA PASTICCERIA","LE PARFAIT","LEAN CUISINE","LEISI","LITORAL","MCCAIN","MILOTAL","SOLIS","STOUFFER’S","STOUFFER'S","TAPUGAN","THOMY","TOMBSTONE","VALSOIA","ZAPETTI","THORCYN","CHEF-MATE","GRATIFY","OF TOV","SUNNY CRACKERS","SABRA SALADS","ESKAL","FRIGEMO","MIGROS","SWEET EARTH","TOTOLE","FRONERI","MAGNUM","5RAMS","AINO","ANTICA GELATERIA DEL CORSO","SIN PARAR","ALASKA","FRIO RICO","PEZIDURI","HÄAGEN DAZS","MÖVENPICK","10-4-2 (TEN FOR TWO)","48 KOPEEK","8 CUBE","APOLO","BEANO","BENNANA","BIG SANDWICH","BUCKINGHAM","BUM BUM","CHENGZHEN","CHRISTIE","CONO","COPPA DEL NONNO","DEL MONTE","DIBS","DISNEY","DREYER'S","DRUMSTICK","EDY'S","ESKI","EXTREME","GELATO","GOLD EDITION","GUMIGUM","HAMSHUSHIM","HUA XIN TONG","JOYA","KIMO","KIMO KONO","KIMY","LA CREMERIA","LA FRUTTA","LUXOR","MATCOOL","MEGA","MICKEY","MOJI","NAPOLINI","OREO","PARLOUR","PAYCO","PIRULO","POPSY","REAL DAIRY","ROLLER","SAVORY","SCHOELLER","SKINNY COW","SQUIZZ","SUNDAE","SUPER CHOCPOP","TEMPTATIONS","TROPICANA","WALNUT WHIP/WHIP","CHAMONIX","OUTSHINE","M&M","MILKA","NUII","TOBLERONE","FROSTY PAWS","NATURE'S HEART","Dysphagia Awareness","Kid Essentials","BUILD UP","NUTRISOURCE","CASEC","GARDEN OF LIFE","ALFAMINO","ALFARE","ALTHERA","BENEPROTEIN","BOOST","CELLTRIENT","CLINUTREN","COMPAT","COMPLEAT","DIABETISOURCE","FIBER MAX","FIBER ONE","FIBREMAIS","IMPACT","ISOCAL","ISOSOURCE","MCT OIL","MERITENE","MODULEN","NESTLÉ HEALTH SCIENCE","NOVASOURCE","NUTREN","OPTIFAST","OPTIFIBRE","ORAL IMPACT","PEPTAMEN","PRONOURISH","RENUTRYL","RESORB","RESOURCE","SONDALIS","SUSTAGEN HOSPITAL FORMULA","THICKENUP","ULTRACAL","VIVONEX","PERSONA","PURE ENCAPSULATIONS","VITAFLO","WOBENZYM","ZENPEP","NESTILLY","COOLPRO","FRUITTIME","RICOFFY","ROMA","SWEET TIME","SUPER SOUP","CUBALUX","EASYWHIP","MCDONALD'S","NESTARGEL","REGILAIT","SAN PELLEGRINO","AMARCREM","BACIO","FORNELLA","JOLLY","LATTE","DANIE W 5 MINUT","JARZYNKA","KOGUTEK","POMYSL NA","SMACZNA ZUPA","SOS ITALIA","CHEF","HAOJI","R001865","MINOR’S","CLIC","KARIMA","NESTLÉ PROFESSIONAL","OSCAR","PUERELL","ROASTELIER","SPLENDA","SUNSATIONAL","VIAGGI","YO-NES","SJORA","CARA","GEORGIA","GFS","CLUB BEBE","MATERNAVIDA","Spoonfulone","1ST FOODS","2ND FOODS","3RD FOODS","BOBO FRUT","FRESHFUL START","GERBER","GOOD START","GRADUATES","LIL MIXERS","PASO 1","PASO 2","BEEP","ALPREM","AL 110","ALETE","ALSOY","BABY","BABY & ME","BABY CEREALS","BABY CLUB","BABY GOURMET","BABYNES","BEBA","BEBE BRAND","BEECH-NUT","BONA","CEREGROW","CRECIMIENTO","EXCEL","EXCELLA GOLD","FM 85","GOOD CARE","GOOD GROW","GROEIE START","GUIGOZ","IOGOLINO","JUNIOR","LACTOGEN","LACTOGROW","LACTOKID","LITTLE STEPS","MATERNA","MATERPLUS","MIO","MOM","MOM&ME","MUCILON","NAN","NANCARE","NANGROW","NANKID","NATIVA","NATURNES","NESLAC","NESTOGEN","NESTOGENO","NESTOGROW","NESTONUTRI","NIDAL","NIDEX","NIDINA","NUTREND","PAPILLAS","PAPINHA","PELARGON","PILTTI","PRELACTOGEN","PRENAN","PRO NATAL","P'TIT DEJ","SINLAC","SMA","Yogolino","AQIVA","ASCENDA","BELSOL","BONAKID","BONAMIL","BONNA","ENERCAL PLUS","ILLUMA","ILLUMCARE","MAMA","PARENTING CLUB","PROMAMA","PROMIL","S-26","S-26 GOLD","SMA GOLD","ULTIMA","WYETH NUTRITION","DELICAT","MILKIES","PETCENTRIC","TREKKER'S","MERRICK PET CARE","LILY’S KITCHEN","WHOLE EARTH FARMS","DOLLAR GENERAL","H.E.BUTT","SHEPHERD","PETFINDER.COM","ZUKES","ADVENTUROS","ALPO","ANDIS","BAKERS","BEGGIN’","BELLA","BENEFUL","BETA","BEYOND","BONIO","BONNIE","BONZO","BUSY","CAMPEON","CASTOR&POLLUX","CAT CHOW","COLLAGEN BEAUTY","COUNTRY FARMS","DARLING","DELI BAKIE","DELI CAT","DENTALIFE","DOG CHOW","DOG MENU","DOGLI","DOGUI","DOGUITOS","DOKO","DROP OF LIFE","DURO DE ROER","EXCEED","EXCELLENT","FANCY FEAST","FELIX","FIDO","FRISKIES","GATI","GATINA","GATSY","GO-CAT","GOURMET","HI PRO","HONEST TO DOG","JUST RIGHT","KANINA","KIT 'N KABOODLE","KITTEN CHOW","K-NINA","LADRINA","LUCKY DOG","LUV","MAINSTAY","MATZINGER","MIGHTY DOG","MOIST & MEATY","MON PETIT","MORDHA","MOREPA","MUSE","NAT","NOBLESSE","OMEGA","ONE","PERRARINA","PETLIFE","PLUSEPA","PRIME BONES","PRO PLAN","PRO PLAN VETERINARY DIETS","PUPPY CHOW","PURINA","SECONDNATURE","SMOOCHIES","SUPERCOAT","TBONZ","THE PIONEER WOMAN","TIDY CATS","TOM POES","TONUS","TOTAL CARE","TUX","VEGANDHA","VETERINARY DIETS","VITAL BALANCE","WAGGIN' TRAIN","WHISKER LICKIN'S","WINALOT","YESTERDAY'S NEWS","TAILS.COM","TERRA CANIS","WAMIZ","ACNECIDE","AZZALURE","BASIRON","BENZAC","CETAPHIL","CLOBEX","DAYLONG","DIFFERIN","DYSPORT","EMERVEL","EPIDUO","EXCIPIAL","GALDERMA","IMAZOL","INNEOV","LACOVIN","LOCERYL","MIRVASO","NEOCAPIL","NUTRAGENT","ONILAQ","ORACEA","PROACTIV","QILIB","RESTYLANE","ROZEX","SOOLANTRA","TRI-LUMA","VECTICAL","VERY BEST BAKERS","SPECIAL.T","ECO DE LOS ANDES","GLACIAR","LA VIE","MYSPRING","AQUAREL","AWAFRUT","BELTE","NESTLE VERA","PULMUONE","PURE LIFE","PUREZA VITAL","SPLASH","ABERFOYLE","ACQUA BRILLANTE","ACQUA PANNA","ALACAM","ARROWHEAD","BBTHE","BUXTON","CALISTOGA","CONTREX","CRISTALP","DEER PARK","DIGER","ERIKLI","GINGERINO","GRANINI","HENNIEZ","HEPAR","ICE MOUNTAIN","KIRKLAND SIGNATURE","KORPI","LEVISSIMA","MINERE","MONTCLAIR","NALECZOWIANKA","OZARKA","PAGO","PERRIER","POLAND SPRING","ROMANETTE","SAN NARCISO","SANBITTER","SANTA MARIA","STA. MARIA","VALVERT","VERA BELTE'","VILADRAU","VITTEL","YUNNAN SHAN QUAN","ZEPHYRHILLS","READY REFRESH","SAO LOURENCO","SOHAT"];
  let scrubbed = string;
  scrubbed = scrubbed

    .replace(/<p><strong>&nbsp;<\/strong><\/p>/g, "")
    .replace(/<strong>&nbsp;<\/strong>/g, "")
    .replace(/<p>&nbsp;<\/p>/g, "")
    .replace(/<h1>&nbsp;<\/h1>/g, "")
    .replace(/<h2>&nbsp;<\/h2>/g, "")
    .replace(/<h3>&nbsp;<\/h3>/g, "")
    .replace(/<h4>&nbsp;<\/h4>/g, "")
    .replace(/<h5>&nbsp;<\/h5>/g, "")
    .replace(/<(h[^>])+><strong>(.*)<\/strong><\/h[^>]+>/g, "<$1>$2</$1>")
    .replace(/<(h[^>])+><em>(.*)<\/em><\/h[^>]+>/g, "<$1>$2</$1>")
    .replace(/<(table|td|tr|th)\s+width="(\d+?)">/g, "<$1>")
    .replace(/<\/strong><strong>/g, "")
    .replace(/&ndash;ndash;/g, "&mdash;")
    .replace(/\n\n\n/g, "\n\n")
    .replace(/\n\n/g, "\n")
    .replace(
      /&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/g,
      "&nbsp;"
    )
    .replace(
      /&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/g,
      "&nbsp;"
    )
    .replace(/&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/g, "&nbsp;")
    .replace(/&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/g, "&nbsp;")
    .replace(/&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/g, "&nbsp;")
    .replace(/&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/g, "&nbsp;")
    .replace(/&nbsp;&nbsp;&nbsp;&nbsp;/g, "&nbsp;")
    .replace(/&nbsp;&nbsp;&nbsp;/g, "&nbsp;")
    .replace(/&nbsp;&nbsp;/g, "&nbsp;")
    .replace(/&nbsp;/g, " ");

  let resultBrands = scrubbed;
  for (let i in brandsArray) {
    resultBrands = resultBrands.replace(
      new RegExp('\\b' + brandsArray[i] + '\\b', 'gi'),
      "<i>"+brandsArray[i]+"</i>"
    );
  }
  scrubbed = resultBrands;
  return resultBrands;

  //взяли ми такі все поміняли, і після цього поміняли бренди з масива
}

// function brands(string) {
//   brandsArray = ["Lion","Kit Kat", "Gerber", "Test", "full"];
//   let resultBrands = string;
//   for (let i in brandsArray) {
//   resultBrands = resultBrands.replace(new RegExp('('+brandsArray[i]+')(?!<\\/b>)', "i"), "<em>$1</em>");
//   }
//   }

function regexEscape(string) {
  return string.replace(/[-/\\^$*+?.()|[\]{}]/g, "\\$&");
}

function reg(string) {
  var escaped = string;
  var flags = "g";
  var escapedNum = Number;
  escaped = regexEscape(escaped);
  escaped = "https?://" + escaped;
  ++escapedNum;
  console.log(escapedNum);
  return new RegExp(escaped, flags);
}

function addDomainFilter(string, domain) {
  var filtered = string;
  var domainregex = reg(domain);

  filtered = filtered.replace(domainregex, "");

  return filtered;
}

function addTargetBlank(string) {
  var plusTarget = string;

  plusTarget = plusTarget.replace(
    /<(a\s+(?:[^>]*?\s+)?href="https?([^"]*)")/g,
    '<$1 target="_blank" class="externalLink"'
  );

  return plusTarget;
}

function clearBoth() {
  CKEDITOR.instances.wordup.setData("");
  document.getElementById("output").value = "";
}

function wordup() {
  var pasteData = CKEDITOR.instances.wordup.getData();

  pasteData = scrubber(pasteData);

  if (
    document.getElementById("domainfilter").checked === true &&
    document.getElementById("domainname").value
  ) {
    pasteData = addDomainFilter(
      pasteData,
      document.getElementById("domainname").value
    );
  }

  if (document.getElementById("targetblank").checked === true) {
    pasteData = addTargetBlank(pasteData);
  }

  if (document.getElementById("markdown").checked === true) {
    pasteData = turndownService.turndown(pasteData);
  }

  document.getElementById("output").value = pasteData;
}
document.getElementById("clear").addEventListener("click", clearBoth);
document.getElementById("convert").addEventListener("click", wordup);
document.getElementById("targetblank").addEventListener("click", wordup);
document.getElementById("markdown").addEventListener("click", wordup);
document.getElementById("domainfilter").addEventListener("click", wordup);
